version: "2.26"
services:
  source:
    build: ../part5
    restart: no
    container_name: source
  resipient:
    image: nginx:latest
    restart: no
    volumes:
      - ./resipient/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    container_name: resipient
